name: CF CDN Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  cdnip:
    runs-on: ubuntu-latest
    name: Scan CDN

    steps:
      - name: ğŸ“‚ Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install Dependencies
        run: python -m pip install --upgrade pip requests

      - name: â–¶ï¸ Run CF CDN Scan
        run: python ./cdnip/main.py

      - name: ğŸ“¤ Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cdnip/data.json
          if ! git diff --cached --quiet; then
            git commit -m "ğŸ” Auto-update cdnip list [$(date -u)]"
            git pull --rebase origin main
            git push origin main
          else
            echo "âœ… No changes to cdnip list."
          fi
