name: CF Proxy Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 0 * * *"

jobs:
  proxyip:
    runs-on: ubuntu-latest
    name: Scan Proxy

    steps:
      - name: ğŸ“‚ Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install Dependencies
        run: python -m pip install --upgrade pip

      - name: â–¶ï¸ Run CF Proxy Scan
        run: python ./proxyip/main.py

      - name: ğŸ“¤ Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxyip/data.json
          if ! git diff --cached --quiet; then
            git commit -m "ğŸ” Auto-update proxyip list [$(date -u)]"
            git pull --rebase origin main
            git push origin main
          else
            echo "âœ… No changes to proxyip list."
          fi
