name: CF Proxy Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  proxyip:
    runs-on: ubuntu-latest
    name: Check Proxy
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: ğŸ“‚ Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./proxyip/requirements.txt

      - name: â–¶ï¸ Run CF Proxy Check
        run: python ./proxyip/main.py

      - name: ğŸ“‹ Group CF Proxy Data
        run: python ./proxyip/ipdb.py

      - name: ğŸ“¤ Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxyip/data.json
          git add proxyip/proxyip.db
          git add proxyip/data/
          if ! git diff --cached --quiet; then
            git commit -m "ğŸ” Auto-update proxyip list [$(date -u)]"
            git pull --rebase origin main
            git push origin main
          else
            echo "âœ… No changes to proxyip list."
          fi
